packages:
  - "nextjs-app"
allowBuilds:
  core-js: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - core-js
  - protobufjs
  - sharp
  - unrs-resolver
